import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
	title: 'Terms of Service | AuditToPitch Pro',
	description: 'Read the terms that apply to your use of AuditToPitch Pro.',
}

const sections = [
	{
		title: '1. Acceptance of Terms',
		content: (
			<p>
				By creating an AuditToPitch Pro account or installing or using the AuditToPitch Pro Chrome extension, you agree to these Terms of Service. If you do not agree, do not use the service.
			</p>
		),
	},
	{
		title: '2. Description of Service',
		content: (
			<p>
				AuditToPitch Pro provides automated website technical audits, detection of signals such as analytics, advertising pixels, and structured data, and AI-generated client pitch scripts. Results are based on information available to the scanner and may not identify every issue or signal on a website.
			</p>
		),
	},
	{
		title: '3. Accounts and Subscriptions',
		content: (
			<p>
				Accounts are managed through Supabase. You are responsible for keeping your sign-in credentials secure and for activity under your account. Paid subscriptions and recurring billing are handled by authorized third-party payment processors. You can cancel a subscription at any time; access and billing after cancellation are subject to the processor&apos;s terms and the status of your current billing period.
			</p>
		),
	},
	{
		title: '4. Acceptable Use',
		content: (
			<p>
				Use the scanner only for lawful purposes and in a way that respects website owners and applicable access restrictions. You must not use AuditToPitch Pro for malicious or unauthorized scraping, denial-of-service attacks, to interfere with a website or its users, or for any unlawful activity. You are responsible for having permission to audit sites where permission is required.
			</p>
		),
	},
	{
		title: '5. AI Output Disclaimer',
		content: (
			<p>
				Audit reports and pitch scripts are generated by automated systems and are intended as prospecting guidance. They may be incomplete or inaccurate and should be reviewed before use. The service is provided on an “as is” and “as available” basis, to the extent permitted by law. We do not guarantee that using an audit or pitch script will convert a prospect into a client.
			</p>
		),
	},
	{
		title: '6. Intellectual Property',
		content: (
			<p>
				As between you and AuditToPitch Pro, you retain ownership of the client reports and pitch scripts generated for your agency outreach. You are responsible for ensuring that your use of generated materials complies with applicable laws and does not infringe another party&apos;s rights. AuditToPitch Pro and its underlying software, branding, and service remain the property of their respective owners.
			</p>
		),
	},
	{
		title: '7. Limitation of Liability',
		content: (
			<p>
				To the maximum extent permitted by applicable law, AuditToPitch Pro and its operators are not liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenue, data, or business opportunities arising from your use of the service. Nothing in these Terms limits liability that cannot legally be limited.
			</p>
		),
	},
	{
		title: '8. Contact and Governing Law',
		content: (
			<p>
				For support questions about these Terms or the service, contact{' '}
				<a href="mailto:support@audittopitch.com" className="font-medium text-brand-light underline decoration-brand/40 underline-offset-4 hover:text-brand">
					support@audittopitch.com
				</a>. These Terms are subject to the laws that apply to your use of the service, including any non-waivable consumer protections in your jurisdiction.
			</p>
		),
	},
]

export default function TermsPage() {
	return (
		<main className="min-h-screen px-4 py-12 sm:py-16">
			<article className="mx-auto max-w-4xl">
				<Link
					href="/"
					className="inline-flex min-h-10 items-center gap-2 rounded-md border border-line bg-surface/80 px-4 text-sm font-medium text-ink transition hover:border-brand/60 hover:text-brand-light focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand"
				>
					<span aria-hidden="true">←</span> Back to Home
				</Link>

				<header className="mt-10 border-b border-line pb-8">
					<p className="text-xs font-semibold uppercase text-brand-light">AuditToPitch Pro</p>
					<h1 className="mt-3 text-4xl font-bold text-ink sm:text-5xl">Terms of Service</h1>
					<p className="mt-4 max-w-2xl text-base leading-7 text-muted">
						These terms explain the rules for using AuditToPitch Pro and its Chrome extension.
					</p>
				</header>

				<div className="divide-y divide-line">
					{sections.map(({ title, content }) => (
						<section key={title} className="py-7 sm:py-8">
							<h2 className="text-xl font-semibold text-ink">{title}</h2>
							<div className="mt-3 space-y-3 text-sm leading-7 text-muted [&_strong]:font-semibold [&_strong]:text-ink">
								{content}
							</div>
						</section>
					))}
				</div>
			</article>
		</main>
	)
}
